import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Nav from './nav';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}

export async function generateMetadata(props: any) {
  console.log('===generateMetadata props', props);

  return {
    title: "Warryy's Next App Demo",
    description: 'Generated by warryy',
  };
}
